version: "2.1"
orbs:
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  UI:
    docker:
      - image: cimg/node:21.6.1-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: "118.0.5993.88"
      - run:
          name: Install Dependencies
          working_directory: UI
          command: npm install
      - run:
          name: Run tests
          working_directory: UI
          command: npm run testHeadless

workflows:
  test:
    jobs:
      - UI
