version: "2.1"
orbs:
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  UI:
    docker:
      - image: cimg/node:21.6.1-browsers
    working_directory: UI
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: "118.0.5993.88"
      - run:
          name: Install Dependencies
          command: npm install

workflows:
  test:
    jobs:
      - UI
