version: "2.1"
orbs:
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  UI:
    docker:
      - image: cimg/node:21.6.1-browsers
    working_directory: SDET-2024/UI
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: "118.0.5993.88"
      - run:
          name: Install Dependencies
          working_directory: SDET-2024/UI
          command: ls && npm install

workflows:
  test:
    jobs:
      - UI
